version: 3.8
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

 backend:
   container_name: backend
   build: ./backend
   env_file:
     - ./backend/ .env.sample
   ports:
     - "8080:8080"
   depends_on:
     - postgress

 frontend:
   container_name: frontend
   build: ./frontend
   env_file:
     - ./backend/ .env.sample
   ports:
     - "3000:3000"
