version: '3.9'

services:
  playground-web-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  playground-web-backend:
    build: 
      context: ./backend
      args:
        GO_VERSION: "1.19"
    environment:
      DB_HOST: "playground-web-db"  # Using the service name as the host
      DB_USER: ${DB_USER}           # Using environment variables for database username
      DB_PASSWORD: ${DB_PASSWORD}   # Using environment variables for database password
      DB_NAME: ${DB_NAME}           # Using environment variables for database name
      DB_PORT: "5432"               # PostgreSQL default port
    ports:
      - "8080:8080"

  playground-web-frontend:
    build: ./frontend
    environment:
      REACT_APP_BACKEND_URL: "http://playground-web-backend:8080"
    ports:
      - "3000:3000"
