version: '3.9'

services:
  playground-web-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  playground-web-backend:
    build: 
      context: ./backend
      args:
        GO_VERSION: "1.19"
    environment:
      DATABASE_URL: "host=playground-web-db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"

  playground-web-frontend:
    build: ./frontend
    environment:
      REACT_APP_BACKEND_URL: "http://playground-web-backend:8080"
    ports:
      - "3000:3000"
